### ISSUE TITLE
Contraseña sin encriptar

### ISSUE THREAD

**Issue by Rocker506** [Rocker506/becademic#2]
Cuando se genera un nuevo usuario la contraseña no le es encriptada.

**Comment by jeanmaradiaga** [comment]
No lo pude probar en la computadora de Cefontec, pero siguiendo una version de mi codigo que si hacia eso anteriormente resolvi el problema. Basicamente alguien le paso por encima a una linea de codigo, ahora antes de mandar a crear el objeto la contraseña generada aleatoriamente se pasa al metodo de encriptación.
